# Generated by Django 5.2.3 on 2025-07-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventario',
            name='codigo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inventario',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventario',
            name='tamano',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='inventario',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
