# Generated by Django 5.2.3 on 2025-10-05 23:07

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='document_type',
            field=models.CharField(choices=[('cc', 'Cédula de Ciudadanía'), ('ce', 'Cédula de Extranjería'), ('nit', 'NIT'), ('ti', 'Tarjeta de Identidad'), ('pasaporte', 'Pasaporte'), ('other', 'Otro')], default='cc', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='part',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='compatible_models',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='part',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='part',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='part',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='min_stock_level',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='part',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='part',
            name='warranty_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='part',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workshop',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='workshop',
            name='dian_resolution_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='dian_resolution_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='dian_resolution_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workshop',
            name='invoice_footer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='invoice_prefix',
            field=models.CharField(default='F', max_length=10),
        ),
        migrations.AddField(
            model_name='workshop',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='workshop',
            name='payment_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='tax_regime',
            field=models.CharField(choices=[('comun', 'Régimen Común'), ('simplificado', 'Régimen Simplificado'), ('especial', 'Régimen Especial')], default='comun', max_length=20),
        ),
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.CharField(choices=[('motor', 'Motor'), ('transmision', 'Transmisión'), ('frenos', 'Frenos'), ('suspension', 'Suspensión'), ('electrico', 'Sistema Eléctrico'), ('carroceria', 'Carrocería'), ('accesorios', 'Accesorios'), ('lubricantes', 'Lubricantes'), ('filtros', 'Filtros'), ('neumaticos', 'Neumáticos'), ('other', 'Otro')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='subscription_expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 4, 23, 7, 17, 851647, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('workshop', 'document_type', 'document_number')},
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('workshop', 'part_number')},
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('consecutive_number', models.IntegerField()),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('workshop_nit', models.CharField(max_length=20)),
                ('workshop_name', models.CharField(max_length=255)),
                ('workshop_address', models.TextField()),
                ('workshop_phone', models.CharField(blank=True, max_length=20)),
                ('workshop_email', models.EmailField(blank=True, max_length=254)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_document', models.CharField(blank=True, max_length=20)),
                ('customer_address', models.TextField(blank=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Pago Parcial'), ('paid', 'Pagada'), ('overdue', 'Vencida'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('check', 'Cheque'), ('other', 'Otro')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='workshops.customer')),
                ('work_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='workshops.workorder')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='workshops.workshop')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit_note_number', models.CharField(max_length=20, unique=True)),
                ('consecutive_number', models.IntegerField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_document', models.CharField(blank=True, max_length=20)),
                ('reason', models.CharField(choices=[('cargo_adicional', 'Cargo adicional'), ('intereses', 'Intereses por mora'), ('cambio_precio', 'Cambio de precio'), ('servicio_extra', 'Servicio adicional'), ('error_factura', 'Corrección de error'), ('other', 'Otro')], max_length=20)),
                ('reason_description', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='workshops.workshop')),
                ('original_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='workshops.invoice')),
            ],
            options={
                'db_table': 'debit_notes',
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_note_number', models.CharField(max_length=20, unique=True)),
                ('consecutive_number', models.IntegerField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_document', models.CharField(blank=True, max_length=20)),
                ('reason', models.CharField(choices=[('devolucion', 'Devolución de producto'), ('descuento', 'Descuento aplicado'), ('error_factura', 'Error en facturación'), ('cambio', 'Cambio de producto'), ('garantia', 'Producto en garantía'), ('other', 'Otro')], max_length=20)),
                ('reason_description', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='workshops.workshop')),
                ('original_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='workshops.invoice')),
            ],
            options={
                'db_table': 'credit_notes',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='workshops.invoice')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_details', to='workshops.part')),
            ],
            options={
                'db_table': 'invoice_details',
            },
        ),
    ]
