# Generated by Django 5.2.3 on 2025-10-14 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_alter_workshop_subscription_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dianconfiguration',
            name='software_id',
            field=models.CharField(default='710d99d0-6d49-4e18-bb70-196d1b17785f', max_length=100),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='software_pin',
            field=models.CharField(default='12345', max_length=100),
        ),
        migrations.AlterField(
            model_name='dianconfiguration',
            name='software_security_code',
            field=models.TextField(default='cfb3e564f5660585cd0ba4f23090242a73d3f4f298110d2eaa3976ce03cba4c6f980f6fa9a41b68a072d8e7decbd53a8'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='subscription_expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 13, 21, 16, 14, 805554, tzinfo=datetime.timezone.utc)),
        ),
    ]
