# Generated by Django 5.2.3 on 2025-10-15 00:02

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_alter_dianconfiguration_software_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='subscription_expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 0, 2, 32, 59962, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('motorcycle', 'Motocicleta'), ('car', 'Automóvil'), ('truck', 'Camión'), ('bicycle', 'Bicicleta'), ('other', 'Otro')], default='motorcycle', max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=50)),
                ('license_plate', models.CharField(blank=True, help_text='Placa o matrícula', max_length=15)),
                ('vin', models.CharField(blank=True, help_text='Número de chasis/VIN', max_length=17)),
                ('engine_number', models.CharField(blank=True, max_length=50)),
                ('mileage', models.IntegerField(default=0, help_text='Kilometraje actual')),
                ('fuel_type', models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diésel'), ('electrico', 'Eléctrico'), ('hibrido', 'Híbrido'), ('gas', 'Gas Natural'), ('other', 'Otro')], default='gasolina', max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatico', 'Automático'), ('cvt', 'CVT'), ('semi-automatico', 'Semi-automático')], default='manual', max_length=20)),
                ('cylinder_capacity', models.IntegerField(blank=True, help_text='Cilindraje en CC', null=True)),
                ('doors', models.IntegerField(blank=True, help_text='Número de puertas', null=True)),
                ('passengers', models.IntegerField(blank=True, help_text='Número de pasajeros', null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_mileage', models.IntegerField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Observaciones sobre el vehículo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='workshops.customer')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='workshops.workshop')),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['-updated_at'],
                'unique_together': {('workshop', 'vin')},
            },
        ),
        migrations.DeleteModel(
            name='Motorcycle',
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('workshops.vehicle',),
        ),
    ]
