# Generated by Django 5.2.3 on 2025-10-15 00:07

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_create_vehicle_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='subscription_expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 0, 7, 56, 66104, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('document_type', models.CharField(choices=[('cc', 'Cédula de Ciudadanía'), ('ce', 'Cédula de Extranjería'), ('nit', 'NIT'), ('ti', 'Tarjeta de Identidad'), ('pasaporte', 'Pasaporte'), ('other', 'Otro')], default='cc', max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=20)),
                ('specialization', models.CharField(choices=[('general', 'Mecánico General'), ('motorcycle', 'Especialista en Motocicletas'), ('engine', 'Motor y Transmisión'), ('electrical', 'Sistema Eléctrico'), ('brakes', 'Frenos y Suspensión'), ('bodywork', 'Carrocería y Pintura'), ('diagnostic', 'Diagnóstico Electrónico'), ('maintenance', 'Mantenimiento Preventivo')], default='general', max_length=20)),
                ('experience_level', models.CharField(choices=[('junior', 'Principiante (0-2 años)'), ('intermediate', 'Intermedio (2-5 años)'), ('senior', 'Senior (5-10 años)'), ('expert', 'Experto (10+ años)')], default='junior', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_available', models.BooleanField(default=True)),
                ('max_daily_hours', models.IntegerField(default=8)),
                ('current_workload', models.IntegerField(default=0)),
                ('certifications', models.TextField(blank=True, help_text='Certificaciones obtenidas')),
                ('training_completed', models.TextField(blank=True, help_text='Capacitaciones realizadas')),
                ('total_work_orders', models.IntegerField(default=0)),
                ('completed_work_orders', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanics', to='workshops.workshop')),
            ],
            options={
                'db_table': 'mechanics',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
