# Generated by Django 5.2.3 on 2025-10-15 00:11

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0006_create_mechanic_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='subscription_expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 0, 11, 52, 836398, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('service_code', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('maintenance', 'Mantenimiento'), ('repair', 'Reparación'), ('diagnostic', 'Diagnóstico'), ('emergency', 'Emergencia'), ('modification', 'Modificación'), ('inspection', 'Inspección'), ('cleaning', 'Limpieza'), ('other', 'Otro')], default='repair', max_length=20)),
                ('applicable_vehicle_types', models.CharField(choices=[('motorcycle', 'Motocicleta'), ('car', 'Automóvil'), ('truck', 'Camión'), ('all', 'Todos los tipos')], default='motorcycle', max_length=20)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('required_skills', models.CharField(blank=True, max_length=100)),
                ('compatible_brands', models.TextField(blank=True)),
                ('required_tools', models.TextField(blank=True)),
                ('warranty_months', models.IntegerField(default=0)),
                ('priority_level', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta'), (4, 'Urgente')], default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_taxable', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('times_used', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='workshops.workshop')),
            ],
            options={
                'db_table': 'services',
                'ordering': ['category', 'name'],
                'unique_together': {('workshop', 'service_code')},
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('internal_code', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('motor', 'Motor'), ('transmision', 'Transmisión'), ('frenos', 'Frenos'), ('suspension', 'Suspensión'), ('electrico', 'Sistema Eléctrico'), ('carroceria', 'Carrocería'), ('accesorios', 'Accesorios'), ('lubricantes', 'Lubricantes'), ('filtros', 'Filtros'), ('neumaticos', 'Neumáticos'), ('other', 'Otro')], default='other', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('compatible_models', models.TextField(blank=True)),
                ('applicable_vehicle_types', models.CharField(choices=[('motorcycle', 'Motocicleta'), ('car', 'Automóvil'), ('truck', 'Camión'), ('all', 'Todos los tipos')], default='motorcycle', max_length=20)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('min_stock_level', models.IntegerField(default=5)),
                ('max_stock_level', models.IntegerField(default=50)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('supplier_code', models.CharField(blank=True, max_length=50)),
                ('warranty_months', models.IntegerField(default=0)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_taxable', models.BooleanField(default=True)),
                ('requires_special_storage', models.BooleanField(default=False)),
                ('times_used', models.IntegerField(default=0)),
                ('total_sold', models.IntegerField(default=0)),
                ('last_sale_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='workshops.workshop')),
            ],
            options={
                'db_table': 'spare_parts',
                'ordering': ['category', 'name'],
                'unique_together': {('workshop', 'internal_code')},
            },
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('workshops.sparepart',),
        ),
    ]
