# Generated by Django 5.2.3 on 2025-10-15 00:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0007_create_service_and_sparepart_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='motorcycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='workshops.vehicle'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='workshops.mechanic'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='actual_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='workorder',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='assigned_mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='workshops.mechanic'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workorder',
            name='customer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='documents',
            field=models.JSONField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='estimated_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='workorder',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='workorder',
            name='final_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='workorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='workorder',
            name='mileage_at_entry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='mileage_at_exit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='parts_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='workorder',
            name='photos_after',
            field=models.JSONField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='photos_before',
            field=models.JSONField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='workorder',
            name='quality_check_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='quality_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('approved', 'Aprobada'), ('in_progress', 'En Progreso'), ('quality_check', 'Control de Calidad'), ('completed', 'Completada'), ('invoiced', 'Facturada'), ('cancelled', 'Cancelada')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='workorder',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='title',
            field=models.CharField(help_text='Título breve del trabajo', max_length=200),
        ),
        migrations.AddField(
            model_name='workorder',
            name='total_parts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='total_services',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='workshops.vehicle'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='warranty_period_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='workshops.workshop'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='final_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('approved', 'Aprobada'), ('in_progress', 'En Progreso'), ('quality_check', 'Control de Calidad'), ('completed', 'Completada'), ('invoiced', 'Facturada'), ('cancelled', 'Cancelada')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkOrderStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('approved', 'Aprobada'), ('in_progress', 'En Progreso'), ('quality_check', 'Control de Calidad'), ('completed', 'Completada'), ('invoiced', 'Facturada'), ('cancelled', 'Cancelada')], max_length=20)),
                ('new_status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('approved', 'Aprobada'), ('in_progress', 'En Progreso'), ('quality_check', 'Control de Calidad'), ('completed', 'Completada'), ('invoiced', 'Facturada'), ('cancelled', 'Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workshops.user')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='workshops.workorder')),
            ],
            options={
                'db_table': 'work_order_status_logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['workshop', 'status'], name='workshops_w_workshop_1b8e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['customer', 'created_date'], name='workshops_w_customer_8b8e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['assigned_mechanic', 'status'], name='workshops_w_assigned_8b8e4c_idx'),
        ),
    ]
