# Generated by Django 5.2.3 on 2025-10-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0007_create_service_and_sparepart_models'),
    ]

    operations = [
    ]
