# Generated by Django 5.2.3 on 2025-10-15 00:24

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0008_create_workorder_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('service', 'Servicio'), ('part', 'Repuesto'), ('labor', 'Mano de Obra'), ('other', 'Otro')], default='service', max_length=10)),
                ('description', models.TextField(help_text='Descripción detallada del ítem')),
                ('part_number', models.CharField(blank=True, help_text='Número de parte o código', max_length=100)),
                ('service_quantity', models.DecimalField(decimal_places=2, default=1, help_text='Cantidad de servicios (horas)', max_digits=6)),
                ('part_quantity', models.IntegerField(default=1, help_text='Cantidad de repuestos')),
                ('service_unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Precio por hora de servicio', max_digits=10)),
                ('part_unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario del repuesto', max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costo total de mano de obra', max_digits=12)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costo total de repuestos', max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costo total del ítem', max_digits=12)),
                ('estimated_time_hours', models.DecimalField(decimal_places=2, default=0, help_text='Tiempo estimado en horas', max_digits=4)),
                ('actual_time_hours', models.DecimalField(decimal_places=2, default=0, help_text='Tiempo real en horas', max_digits=4)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales del ítem')),
                ('inventory_updated', models.BooleanField(default=False, help_text='Si el inventario ya fue actualizado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'work_order_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='workorderdetail',
            name='part',
        ),
        migrations.RemoveField(
            model_name='workorderdetail',
            name='work_order',
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='work_orders_worksho_4553eb_idx',
            old_name='workshops_w_workshop_1b8e4c_idx',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='work_orders_custome_341d24_idx',
            old_name='workshops_w_customer_8b8e4c_idx',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='work_orders_assigne_86bdad_idx',
            old_name='workshops_w_assigned_8b8e4c_idx',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='motorcycle',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Notas para el cliente'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción detallada del problema'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='diagnosis',
            field=models.TextField(blank=True, help_text='Diagnóstico realizado'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='documents',
            field=models.JSONField(blank=True, help_text='URLs de documentos adjuntos'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Notas internas del taller'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='mileage_at_entry',
            field=models.IntegerField(blank=True, help_text='Kilometraje al ingreso', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='mileage_at_exit',
            field=models.IntegerField(blank=True, help_text='Kilometraje al egreso', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='photos_after',
            field=models.JSONField(blank=True, help_text='URLs de fotos después del trabajo'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='photos_before',
            field=models.JSONField(blank=True, help_text='URLs de fotos antes del trabajo'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Síntomas reportados por el cliente'),
        ),
        migrations.AlterField(
            model_name='workorderstatuslog',
            name='new_status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('approved', 'Aprobada'), ('in_progress', 'En Progreso'), ('quality_check', 'Control de Calidad'), ('completed', 'Completada'), ('invoiced', 'Facturada'), ('cancelled', 'Cancelada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='subscription_expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 0, 24, 23, 846160, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_items', to='workshops.sparepart'),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_items', to='workshops.service'),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='workshops.workorder'),
        ),
        migrations.DeleteModel(
            name='WorkOrderDetail',
        ),
        migrations.CreateModel(
            name='WorkOrderDetail',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('workshops.workorderitem',),
        ),
    ]
