# Generated by Django 5.2.3 on 2025-10-15 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0008_auto_20251014_2053'),
    ]

    operations = [
    ]
