# Generated by Django 5.2.3 on 2025-10-15 00:27

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0009_create_workorderitem_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='subscription_expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 14, 0, 27, 53, 597026, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quotation_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(help_text='Título de la cotización', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción general de los trabajos')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('expired', 'Expirada'), ('converted', 'Convertida a OT')], default='draft', max_length=15)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Fecha de expiración', null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('estimated_labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Descuento en porcentaje', max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Descuento en valor absoluto', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Valor de IVA', max_digits=12)),
                ('final_total', models.DecimalField(decimal_places=2, default=0, help_text='Total final con descuentos e IVA', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales')),
                ('terms_conditions', models.TextField(blank=True, help_text='Términos y condiciones')),
                ('times_viewed', models.IntegerField(default=0)),
                ('last_viewed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_to_work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotation', to='workshops.workorder')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='workshops.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='workshops.vehicle')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='workshops.workshop')),
            ],
            options={
                'db_table': 'quotations',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('service', 'Servicio'), ('part', 'Repuesto'), ('labor', 'Mano de Obra'), ('other', 'Otro')], default='service', max_length=10)),
                ('description', models.TextField(help_text='Descripción detallada del ítem')),
                ('service_quantity', models.DecimalField(decimal_places=2, default=1, help_text='Cantidad de servicios (horas)', max_digits=6)),
                ('part_quantity', models.IntegerField(default=1, help_text='Cantidad de repuestos')),
                ('service_unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Precio por hora de servicio', max_digits=10)),
                ('part_unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario del repuesto', max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costo total de mano de obra', max_digits=12)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costo total de repuestos', max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costo total del ítem', max_digits=12)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, help_text='Tiempo estimado en horas', max_digits=4)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='workshops.sparepart')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workshops.quotation')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='workshops.service')),
            ],
            options={
                'db_table': 'quotation_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['workshop', 'status'], name='quotations_worksho_5d1283_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['customer', 'created_date'], name='quotations_custome_d1f3da_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['valid_until', 'status'], name='quotations_valid_u_d23db7_idx'),
        ),
    ]
