# Generated by Django 5.2.3 on 2025-10-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0010_auto_20251014_2059'),
    ]

    operations = [
        # Rename field completion_date to warranty_start_date on workorder
        migrations.RenameField(
            model_name='workorder',
            old_name='completion_date',
            new_name='warranty_start_date',
        ),
    ]
