# Generated by Django 5.2.3 on 2025-10-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0011_auto_20251016_1118'),
    ]

    operations = [
    ]
