# Generated by Django 5.2.3 on 2025-10-16 16:24

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0012_auto_20251016_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quotation_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(help_text='Título de la cotización', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción general de los trabajos')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('expired', 'Expirada'), ('converted', 'Convertida a OT')], default='draft', max_length=15)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Fecha de expiración', null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('estimated_labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Descuento en porcentaje', max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Descuento en valor absoluto', max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Valor de IVA', max_digits=12)),
                ('final_total', models.DecimalField(decimal_places=2, default=0, help_text='Total final con descuentos e IVA', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales')),
                ('terms_conditions', models.TextField(blank=True, help_text='Términos y condiciones')),
                ('times_viewed', models.IntegerField(default=0)),
                ('last_viewed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quotations',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('service', 'Servicio'), ('part', 'Repuesto'), ('labor', 'Mano de Obra'), ('other', 'Otro')], default='service', max_length=10)),
                ('description', models.TextField(help_text='Descripción detallada del ítem')),
                ('service_quantity', models.DecimalField(decimal_places=2, default=1, help_text='Cantidad de servicios (horas)', max_digits=6)),
                ('part_quantity', models.IntegerField(default=1, help_text='Cantidad de repuestos')),
                ('service_unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Precio por hora de servicio', max_digits=10)),
                ('part_unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario del repuesto', max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costo total de mano de obra', max_digits=12)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costo total de repuestos', max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costo total del ítem', max_digits=12)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, help_text='Tiempo estimado en horas', max_digits=4)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'quotation_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('service', 'Servicio'), ('part', 'Repuesto'), ('labor', 'Mano de Obra'), ('other', 'Otro')], default='service', max_length=10)),
                ('description', models.TextField(help_text='Descripción detallada del ítem')),
                ('part_number', models.CharField(blank=True, help_text='Número de parte o código', max_length=100)),
                ('service_quantity', models.DecimalField(decimal_places=2, default=1, help_text='Cantidad de servicios (horas)', max_digits=6)),
                ('part_quantity', models.IntegerField(default=1, help_text='Cantidad de repuestos')),
                ('service_unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Precio por hora de servicio', max_digits=10)),
                ('part_unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario del repuesto', max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costo total de mano de obra', max_digits=12)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costo total de repuestos', max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Costo total del ítem', max_digits=12)),
                ('estimated_time_hours', models.DecimalField(decimal_places=2, default=0, help_text='Tiempo estimado en horas', max_digits=4)),
                ('actual_time_hours', models.DecimalField(decimal_places=2, default=0, help_text='Tiempo real en horas', max_digits=4)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales del ítem')),
                ('inventory_updated', models.BooleanField(default=False, help_text='Si el inventario ya fue actualizado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'work_order_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('approved', 'Aprobada'), ('in_progress', 'En Progreso'), ('quality_check', 'Control de Calidad'), ('completed', 'Completada'), ('invoiced', 'Facturada'), ('cancelled', 'Cancelada')], max_length=20)),
                ('new_status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('approved', 'Aprobada'), ('in_progress', 'En Progreso'), ('quality_check', 'Control de Calidad'), ('completed', 'Completada'), ('invoiced', 'Facturada'), ('cancelled', 'Cancelada')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'work_order_status_logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.RemoveField(
            model_name='workorderdetail',
            name='part',
        ),
        migrations.RemoveField(
            model_name='workorderdetail',
            name='work_order',
        ),
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='motorcycle',
        ),
        migrations.AddField(
            model_name='workorder',
            name='actual_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='workorder',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='assigned_mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='workshops.mechanic'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workorder',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Notas para el cliente'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='diagnosis',
            field=models.TextField(blank=True, help_text='Diagnóstico realizado'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='documents',
            field=models.JSONField(blank=True, default=dict, help_text='URLs de documentos adjuntos'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='estimated_completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='workorder',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Notas internas del taller'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='workorder',
            name='mileage_at_entry',
            field=models.IntegerField(blank=True, help_text='Kilometraje al ingreso', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='mileage_at_exit',
            field=models.IntegerField(blank=True, help_text='Kilometraje al egreso', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='parts_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='workorder',
            name='photos_after',
            field=models.JSONField(blank=True, default=dict, help_text='URLs de fotos después del trabajo'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='photos_before',
            field=models.JSONField(blank=True, default=dict, help_text='URLs de fotos antes del trabajo'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='workorder',
            name='quality_check_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='quality_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Síntomas reportados por el cliente'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='title',
            field=models.CharField(default='Orden de Trabajo', help_text='Título breve del trabajo', max_length=200),
        ),
        migrations.AddField(
            model_name='workorder',
            name='total_parts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='total_services',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='workshops.vehicle'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='warranty_period_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción detallada del problema'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='final_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='order_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('approved', 'Aprobada'), ('in_progress', 'En Progreso'), ('quality_check', 'Control de Calidad'), ('completed', 'Completada'), ('invoiced', 'Facturada'), ('cancelled', 'Cancelada')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='subscription_expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 15, 16, 24, 11, 337641, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['workshop', 'status'], name='work_orders_worksho_4553eb_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['customer', 'created_date'], name='work_orders_custome_341d24_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['assigned_mechanic', 'status'], name='work_orders_assigne_86bdad_idx'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='converted_to_work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotation', to='workshops.workorder'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='workshops.customer'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='workshops.vehicle'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='workshops.workshop'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='workshops.sparepart'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workshops.quotation'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='workshops.service'),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_items', to='workshops.sparepart'),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_items', to='workshops.service'),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='workshops.workorder'),
        ),
        migrations.AddField(
            model_name='workorderstatuslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderstatuslog',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='workshops.workorder'),
        ),
        migrations.DeleteModel(
            name='WorkOrderDetail',
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['workshop', 'status'], name='quotations_worksho_5d1283_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['customer', 'created_date'], name='quotations_custome_d1f3da_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['valid_until', 'status'], name='quotations_valid_u_d23db7_idx'),
        ),
        migrations.CreateModel(
            name='WorkOrderDetail',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('workshops.workorderitem',),
        ),
    ]
