# Generated by Django 5.2.3 on 2025-10-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0013_quotation_quotationitem_workorderitem_and_more'),
    ]

    operations = [
        # Renombrar columna motorcycle_id a vehicle_id
        migrations.RunSQL(
            'ALTER TABLE work_orders RENAME COLUMN motorcycle_id TO vehicle_id;',
            reverse_sql='ALTER TABLE work_orders RENAME COLUMN vehicle_id TO motorcycle_id;'
        ),
        # Cambiar assigned_mechanic de employee_id a assigned_mechanic_id
        migrations.RunSQL(
            'ALTER TABLE work_orders RENAME COLUMN employee_id TO assigned_mechanic_id;',
            reverse_sql='ALTER TABLE work_orders RENAME COLUMN assigned_mechanic_id TO employee_id;'
        ),
    ]
