# Generated by Django 5.2.3 on 2025-10-16 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0013_quotation_quotationitem_workorderitem_and_more'),
    ]

    operations = [
        # Todas las operaciones ya fueron aplicadas en despliegues anteriores
        # Esta migración se marca como vacía para evitar conflictos
    ]
