# Generated by Django 5.2.3 on 2025-10-16 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0013_quotation_quotationitem_workorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='title',
            field=models.CharField(default='Orden de Trabajo', help_text='Título breve del trabajo', max_length=200),
        ),
        migrations.AddField(
            model_name='workorder',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Síntomas reportados por el cliente'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='diagnosis',
            field=models.TextField(blank=True, help_text='Diagnóstico realizado'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='workorder',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='workorder',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='workorder',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workorder',
            name='quality_check_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='quality_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='warranty_period_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='photos_before',
            field=models.JSONField(blank=True, default=dict, help_text='URLs de fotos antes del trabajo'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='photos_after',
            field=models.JSONField(blank=True, default=dict, help_text='URLs de fotos después del trabajo'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='documents',
            field=models.JSONField(blank=True, default=dict, help_text='URLs de documentos adjuntos'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Notas internas del taller'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Notas para el cliente'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='total_services',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='total_parts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo total de mano de obra', max_digits=12),
        ),
        migrations.AddField(
            model_name='workorder',
            name='parts_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo total de repuestos', max_digits=12),
        ),
    ]
