# Generated by Django 5.2.3 on 2025-10-16 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0015_add_missing_workorder_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='parts_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='subscription_expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 15, 16, 38, 14, 199220, tzinfo=datetime.timezone.utc)),
        ),
    ]
