# Generated by Django 5.2.3 on 2025-10-16 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0016_alter_workorder_labor_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='subscription_expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 15, 16, 40, 10, 130736, tzinfo=datetime.timezone.utc)),
        ),
    ]
