# Generated by Django 5.2.3 on 2025-10-16 16:41

import uuid
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0017_create_work_order_items_table'),
    ]

    operations = [
        # La tabla work_order_items ya fue creada en despliegues anteriores
        # Esta migración se deja vacía para evitar conflictos
    ]
