# Generated by Django 5.2.3 on 2025-10-16 16:48

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0018_create_work_order_items_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_items', to='workshops.sparepart'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_items', to='workshops.service'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='subscription_expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 15, 16, 48, 40, 419069, tzinfo=datetime.timezone.utc)),
        ),
    ]
