# Generated by Django 5.2.3 on 2025-10-16 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0019_alter_workorderitem_id_alter_workorderitem_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicinvoice',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='subscription_expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 15, 22, 10, 51, 988474, tzinfo=datetime.timezone.utc)),
        ),
    ]
