# Generated by Django 5.2.3 on 2025-10-16 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0020_electronicinvoice_qr_code_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='subscription_expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 15, 22, 30, 34, 918906, tzinfo=datetime.timezone.utc)),
        ),
    ]
