# Generated by Django 5.2.3 on 2025-10-17 21:55

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0021_alter_workshop_subscription_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='employee',
        ),
        migrations.AddField(
            model_name='appointment',
            name='assigned_mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='workshops.mechanic'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email de contacto alternativo', max_length=254),
        ),
        migrations.AddField(
            model_name='appointment',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Teléfono de contacto alternativo', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='converted_to_work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_appointment', to='workshops.workorder'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='custom_service_description',
            field=models.CharField(blank=True, help_text='Descripción si no es un tipo de servicio estándar', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Notas para el cliente'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.IntegerField(default=60, help_text='Duración en minutos'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='workshops.vehicle'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas internas del taller'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Programada'), ('confirmed', 'Confirmada'), ('in_progress', 'En Progreso'), ('completed', 'Completada'), ('no_show', 'No Asistió'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='subscription_expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 16, 21, 55, 46, 493921, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('maintenance', 'Mantenimiento'), ('repair', 'Reparación'), ('diagnostic', 'Diagnóstico'), ('emergency', 'Emergencia'), ('inspection', 'Inspección'), ('other', 'Otro')], default='maintenance', max_length=50)),
                ('estimated_duration', models.IntegerField(default=60, help_text='Duración estimada en minutos')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('color', models.CharField(default='#3b82f6', help_text='Color en formato hex (#RRGGBB)', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_types', to='workshops.workshop')),
            ],
            options={
                'db_table': 'service_types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='workshops.servicetype'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['workshop', 'appointment_date'], name='appointment_worksho_16f3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['assigned_mechanic', 'appointment_date'], name='appointment_assigne_6bc282_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['customer', 'appointment_date'], name='appointment_custome_dfb05a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'appointment_date'], name='appointment_status_06f84b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicetype',
            unique_together={('workshop', 'name')},
        ),
    ]
