# Generated by Django 5.2.3 on 2025-10-17 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0022_remove_appointment_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='workshop',
            name='subscription_expires',
            field=models.DateField(default=datetime.datetime(2025, 11, 16, 22, 50, 57, 905502, tzinfo=datetime.timezone.utc)),
        ),
    ]
