# Generated by Django 5.2.3 on 2025-10-18 22:02

import workshops.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0023_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='subscription_expires',
            field=models.DateField(default=workshops.models.get_default_subscription_expiry),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['workshop', 'document_type', 'document_number'], name='customers_worksho_59fb43_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_email_92e882_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customers_phone_91048b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active', 'workshop'], name='customers_is_acti_7e4fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicinvoice',
            index=models.Index(fields=['workshop', 'dian_status'], name='electronic__worksho_da7d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicinvoice',
            index=models.Index(fields=['invoice_number'], name='electronic__invoice_1e2b95_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicinvoice',
            index=models.Index(fields=['cude'], name='electronic__cude_da9979_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicinvoice',
            index=models.Index(fields=['customer', 'issue_date'], name='electronic__custome_44340b_idx'),
        ),
        migrations.AddIndex(
            model_name='electronicinvoice',
            index=models.Index(fields=['payment_status'], name='electronic__payment_a36283_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['workshop', 'customer'], name='vehicles_worksho_562063_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_plate'], name='vehicles_license_b08e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vin'], name='vehicles_vin_42311c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_active', 'workshop'], name='vehicles_is_acti_149242_idx'),
        ),
    ]
