# Generated by Django 5.2.3 on 2025-10-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0024_add_database_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dianresolution',
            name='alert_sent',
            field=models.BooleanField(default=False, help_text='Si ya se envió alerta de uso'),
        ),
        migrations.AddField(
            model_name='dianresolution',
            name='alert_threshold_percentage',
            field=models.IntegerField(default=75, help_text='Porcentaje para alerta de uso'),
        ),
        migrations.AddField(
            model_name='dianresolution',
            name='last_number_assigned_at',
            field=models.DateTimeField(blank=True, help_text='Última vez que se asignó un número', null=True),
        ),
        migrations.AddField(
            model_name='dianresolution',
            name='technical_key',
            field=models.CharField(blank=True, help_text='Clave técnica asignada por DIAN', max_length=255),
        ),
        migrations.AddField(
            model_name='dianresolution',
            name='total_numbers_assigned',
            field=models.IntegerField(default=0, help_text='Total de números asignados'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='organization_type',
            field=models.CharField(choices=[('1', 'Persona Jurídica'), ('2', 'Persona Natural')], default='1', help_text='Tipo de organización para facturación electrónica', max_length=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='tax_responsibilities',
            field=models.JSONField(blank=True, default=list, help_text="Lista de códigos de responsabilidades fiscales DIAN (ej: ['O-13', 'O-15', 'O-47'])"),
        ),
        migrations.AddIndex(
            model_name='dianresolution',
            index=models.Index(fields=['workshop', 'document_type', 'is_active'], name='dian_resolu_worksho_07000f_idx'),
        ),
        migrations.AddIndex(
            model_name='dianresolution',
            index=models.Index(fields=['expires_date', 'is_active'], name='dian_resolu_expires_ad2c7d_idx'),
        ),
    ]
