# Generated by Django 5.2.3 on 2025-10-19 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0025_add_dian_fiscal_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicinvoicedetail',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electronic_invoice_details', to='workshops.sparepart'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_details', to='workshops.sparepart'),
        ),
    ]
